ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sd_low_power_mode_global_default: "true"
    sku: "configs/sku/innovium.77700_A"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "api_driven"
    max_lossless_tc: "2"
    ilpm_enable: "1"
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    ecn_stats_enable: "1"
    pcie_attn: "10, 0, 0, 0"
    pcie_post: "10, 18, 18, 18"
    pcie_pre1: "0, 0, 0, 0"
    led_cfg_sck_rate: "0x5"
    led_refresh_precliff_timer: "0x18eec2"
    led_refresh_cliff_timer: "0x15e"
    led_cfg_pic_stream_mode: "1"
    led_refresh_tmr_ctl_enable: "1"
    stats_poll_interval: "1000"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39"
    - rxring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40"
    - rxring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 47"
    - rxring_id: "3"
      desc_count: "1024"
      prio: "1"
      queues: "42, 43, 44, 45, 46"
    sys_clk: "1720"
    ifc_clk: "1200"
    mac_clk: "1340"
  devports:
  - id: "0"
    sysport: "1000"
    type: "cpu"
  - id: "89"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "89"
    type: "eth"
  - id: "90"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "90"
    type: "eth"
  - id: "91"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "91"
    type: "eth"
  - id: "92"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "92"
    type: "eth"
  - id: "81"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "10"
    speed: "25G"
    sysport: "81"
    type: "eth"
  - id: "82"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "10"
    speed: "25G"
    sysport: "82"
    type: "eth"
  - id: "83"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "10"
    speed: "25G"
    sysport: "83"
    type: "eth"
  - id: "84"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "10"
    speed: "25G"
    sysport: "84"
    type: "eth"
  - id: "73"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "9"
    speed: "25G"
    sysport: "73"
    type: "eth"
  - id: "74"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "9"
    speed: "25G"
    sysport: "74"
    type: "eth"
  - id: "75"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "9"
    speed: "25G"
    sysport: "75"
    type: "eth"
  - id: "76"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "9"
    speed: "25G"
    sysport: "76"
    type: "eth"
  - id: "65"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "8"
    speed: "25G"
    sysport: "65"
    type: "eth"
  - id: "66"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "8"
    speed: "25G"
    sysport: "66"
    type: "eth"
  - id: "67"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "8"
    speed: "25G"
    sysport: "67"
    type: "eth"
  - id: "68"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "8"
    speed: "25G"
    sysport: "68"
    type: "eth"
  - id: "57"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "7"
    speed: "25G"
    sysport: "57"
    type: "eth"
  - id: "58"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "7"
    speed: "25G"
    sysport: "58"
    type: "eth"
  - id: "59"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "7"
    speed: "25G"
    sysport: "59"
    type: "eth"
  - id: "60"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "7"
    speed: "25G"
    sysport: "60"
    type: "eth"
  - id: "49"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "6"
    speed: "25G"
    sysport: "49"
    type: "eth"
  - id: "50"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "6"
    speed: "25G"
    sysport: "50"
    type: "eth"
  - id: "51"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "6"
    speed: "25G"
    sysport: "51"
    type: "eth"
  - id: "52"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "6"
    speed: "25G"
    sysport: "52"
    type: "eth"
  - id: "41"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "41"
    type: "eth"
  - id: "42"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "42"
    type: "eth"
  - id: "43"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "43"
    type: "eth"
  - id: "44"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "44"
    type: "eth"
  - id: "33"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "4"
    speed: "25G"
    sysport: "33"
    type: "eth"
  - id: "34"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "4"
    speed: "25G"
    sysport: "34"
    type: "eth"
  - id: "35"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "4"
    speed: "25G"
    sysport: "35"
    type: "eth"
  - id: "36"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "4"
    speed: "25G"
    sysport: "36"
    type: "eth"
  - id: "153"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "19"
    speed: "25G"
    sysport: "153"
    type: "eth"
  - id: "154"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "19"
    speed: "25G"
    sysport: "154"
    type: "eth"
  - id: "155"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "19"
    speed: "25G"
    sysport: "155"
    type: "eth"
  - id: "156"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "19"
    speed: "25G"
    sysport: "156"
    type: "eth"
  - id: "145"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "18"
    speed: "25G"
    sysport: "145"
    type: "eth"
  - id: "146"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "18"
    speed: "25G"
    sysport: "146"
    type: "eth"
  - id: "147"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "18"
    speed: "25G"
    sysport: "147"
    type: "eth"
  - id: "148"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "18"
    speed: "25G"
    sysport: "148"
    type: "eth"
  - id: "137"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "17"
    speed: "25G"
    sysport: "137"
    type: "eth"
  - id: "138"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "17"
    speed: "25G"
    sysport: "138"
    type: "eth"
  - id: "139"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "17"
    speed: "25G"
    sysport: "139"
    type: "eth"
  - id: "140"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "17"
    speed: "25G"
    sysport: "140"
    type: "eth"
  - id: "129"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "16"
    speed: "25G"
    sysport: "129"
    type: "eth"
  - id: "130"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "16"
    speed: "25G"
    sysport: "130"
    type: "eth"
  - id: "131"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "16"
    speed: "25G"
    sysport: "131"
    type: "eth"
  - id: "132"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "16"
    speed: "25G"
    sysport: "132"
    type: "eth"
  - id: "121"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "15"
    speed: "25G"
    sysport: "121"
    type: "eth"
  - id: "122"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "15"
    speed: "25G"
    sysport: "122"
    type: "eth"
  - id: "123"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "15"
    speed: "25G"
    sysport: "123"
    type: "eth"
  - id: "124"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "15"
    speed: "25G"
    sysport: "124"
    type: "eth"
  - id: "113"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "113"
    type: "eth"
  - id: "114"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "114"
    type: "eth"
  - id: "115"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "115"
    type: "eth"
  - id: "116"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "116"
    type: "eth"
  - id: "105"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "105"
    type: "eth"
  - id: "106"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "106"
    type: "eth"
  - id: "107"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "107"
    type: "eth"
  - id: "108"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "108"
    type: "eth"
  - id: "97"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "12"
    speed: "25G"
    sysport: "97"
    type: "eth"
  - id: "98"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "12"
    speed: "25G"
    sysport: "98"
    type: "eth"
  - id: "99"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "12"
    speed: "25G"
    sysport: "99"
    type: "eth"
  - id: "100"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "12"
    speed: "25G"
    sysport: "100"
    type: "eth"
  - id: "209"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "26"
    speed: "25G"
    sysport: "209"
    type: "eth"
  - id: "210"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "26"
    speed: "25G"
    sysport: "210"
    type: "eth"
  - id: "211"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "26"
    speed: "25G"
    sysport: "211"
    type: "eth"
  - id: "212"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "26"
    speed: "25G"
    sysport: "212"
    type: "eth"
  - id: "217"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "27"
    speed: "25G"
    sysport: "217"
    type: "eth"
  - id: "218"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "27"
    speed: "25G"
    sysport: "218"
    type: "eth"
  - id: "219"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "27"
    speed: "25G"
    sysport: "219"
    type: "eth"
  - id: "220"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "27"
    speed: "25G"
    sysport: "220"
    type: "eth"
  - id: "193"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "24"
    speed: "100G"
    sysport: "193"
    type: "eth"
  - id: "201"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "25"
    speed: "100G"
    sysport: "201"
    type: "eth"
  - id: "177"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "22"
    speed: "100G"
    sysport: "177"
    type: "eth"
  - id: "185"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "23"
    speed: "100G"
    sysport: "185"
    type: "eth"
  - id: "161"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "20"
    speed: "100G"
    sysport: "161"
    type: "eth"
  - id: "169"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "21"
    speed: "100G"
    sysport: "169"
    type: "eth"
  - id: "17"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "2"
    speed: "100G"
    sysport: "17"
    type: "eth"
  - id: "25"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "3"
    speed: "100G"
    sysport: "25"
    type: "eth"
  - id: "1"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "0"
    speed: "400G"
    sysport: "1"
    type: "eth"
  - id: "9"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "1"
    speed: "400G"
    sysport: "9"
    type: "eth"
  - id: "241"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "30"
    speed: "400G"
    sysport: "241"
    type: "eth"
  - id: "249"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "31"
    speed: "400G"
    sysport: "249"
    type: "eth"
  - id: "225"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "28"
    speed: "400G"
    sysport: "225"
    type: "eth"
  - id: "233"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "29"
    speed: "400G"
    sysport: "233"
    type: "eth"
  isg:
  - id: "11"
    lane_swap: "27163504"
    rx_polarity: "01010000"
    tx_polarity: "01100000"
  - id: "10"
    lane_swap: "51604372"
    rx_polarity: "11001000"
    tx_polarity: "11110000"
  - id: "9"
    lane_swap: "17032546"
    rx_polarity: "10001000"
    tx_polarity: "00000100"
  - id: "8"
    lane_swap: "70435162"
    rx_polarity: "11000100"
    tx_polarity: "00100101"
  - id: "7"
    lane_swap: "27053416"
    rx_polarity: "00011001"
    tx_polarity: "10001000"
  - id: "6"
    lane_swap: "70635142"
    rx_polarity: "10001000"
    tx_polarity: "01100001"
  - id: "5"
    lane_swap: "27053416"
    rx_polarity: "00001001"
    tx_polarity: "00001000"
  - id: "4"
    lane_swap: "62405173"
    rx_polarity: "11000101"
    tx_polarity: "10110000"
  - id: "19"
    lane_swap: "06152347"
    rx_polarity: "11010110"
    tx_polarity: "10001110"
  - id: "18"
    lane_swap: "73614052"
    rx_polarity: "11001100"
    tx_polarity: "11100001"
  - id: "17"
    lane_swap: "17053426"
    rx_polarity: "10001001"
    tx_polarity: "00001000"
  - id: "16"
    lane_swap: "54216073"
    rx_polarity: "10000011"
    tx_polarity: "01001010"
  - id: "15"
    lane_swap: "36072514"
    rx_polarity: "10100000"
    tx_polarity: "10100001"
  - id: "14"
    lane_swap: "50763241"
    rx_polarity: "00010001"
    tx_polarity: "01110001"
  - id: "13"
    lane_swap: "26071435"
    rx_polarity: "00000011"
    tx_polarity: "00101001"
  - id: "12"
    lane_swap: "43510627"
    rx_polarity: "11100100"
    tx_polarity: "00011101"
  - id: "26"
    lane_swap: "31427506"
    rx_polarity: "10011000"
    tx_polarity: "11110001"
  - id: "27"
    lane_swap: "21735406"
    rx_polarity: "01011110"
    tx_polarity: "10011100"
  - id: "24"
    lane_swap: "07162435"
    rx_polarity: "10010000"
    tx_polarity: "10001010"
  - id: "25"
    lane_swap: "64501372"
    rx_polarity: "11010001"
    tx_polarity: "10001010"
  - id: "22"
    lane_swap: "35071624"
    rx_polarity: "00100011"
    tx_polarity: "11001011"
  - id: "23"
    lane_swap: "64705132"
    rx_polarity: "11010100"
    tx_polarity: "11101000"
  - id: "20"
    lane_swap: "16270453"
    rx_polarity: "00101100"
    tx_polarity: "00001001"
  - id: "21"
    lane_swap: "71356204"
    rx_polarity: "01100010"
    tx_polarity: "00001011"
  - id: "2"
    lane_swap: "37260145"
    rx_polarity: "10011010"
    tx_polarity: "11000000"
  - id: "3"
    lane_swap: "47512630"
    rx_polarity: "10010100"
    tx_polarity: "10101101"
  - id: "0"
    lane_swap: "05462713"
    rx_polarity: "01000000"
    tx_polarity: "10010010"
  - id: "1"
    lane_swap: "71605432"
    rx_polarity: "00000000"
    tx_polarity: "11000101"
  - id: "30"
    lane_swap: "37251604"
    rx_polarity: "11000010"
    tx_polarity: "11001000"
  - id: "31"
    lane_swap: "42736051"
    rx_polarity: "10000110"
    tx_polarity: "01000010"
  - id: "28"
    lane_swap: "01245736"
    rx_polarity: "10110101"
    tx_polarity: "10000001"
  - id: "29"
    lane_swap: "52706134"
    rx_polarity: "00010010"
    tx_polarity: "10101010"
