# docker image for teralynx syncd

DOCKER_SYNCD_MRVL_TERALYNX = docker-syncd-mrvl-teralynx.gz

$(DOCKER_SYNCD_MRVL_TERALYNX)_PATH = $(PLATFORM_PATH)/docker-syncd-mrvl-teralynx
$(DOCKER_SYNCD_MRVL_TERALYNX)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
$(DOCKER_SYNCD_MRVL_TERALYNX)_DEPENDS += $(SYNCD) $(PYTHON_SDK_API) $(INVM_LIBSAI) $(INVM_SHELL)

ifeq ($(INSTALL_DEBUG_TOOLS), y)
$(DOCKER_SYNCD_MRVL_TERALYNX)_DBG_DEPENDS += $(SYNCD_DBG) \
					$(LIBSWSSCOMMON_DBG) \
					$(LIBSAIMETADATA_DBG) \
					$(LIBSAIREDIS_DBG)
endif
$(DOCKER_SYNCD_MRVL_TERALYNX)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BOOKWORM)
SONIC_DOCKER_IMAGES += $(DOCKER_SYNCD_MRVL_TERALYNX)

ifneq ($(ENABLE_SYNCD_RPC),y)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_SYNCD_MRVL_TERALYNX)
endif

$(DOCKER_SYNCD_MRVL_TERALYNX)_VERSION = 1.0.0
$(DOCKER_SYNCD_MRVL_TERALYNX)_PACKAGE_NAME = syncd-teralynx
$(DOCKER_SYNCD_MRVL_TERALYNX)_MACHINE = marvell-teralynx
#$(DOCKER_SYNCD_MRVL_TERALYNX)_AFTER = $(DOCKER_SYNCD_BASE)
$(DOCKER_SYNCD_MRVL_TERALYNX)_CONTAINER_NAME = syncd
$(DOCKER_SYNCD_MRVL_TERALYNX)_RUN_OPT += --privileged -t
$(DOCKER_SYNCD_MRVL_TERALYNX)_RUN_OPT += -v /host/machine.conf:/etc/machine.conf
$(DOCKER_SYNCD_MRVL_TERALYNX)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_SYNCD_MRVL_TERALYNX)_RUN_OPT += -v /host/warmboot:/var/warmboot
